name: instant_sos
description: Instant SOS Emergency Alert App
publish_to: 'none'
version: 1.0.0+1

environment:
  # رفعنا الحد الأدنى ليقبل التحديثات الجديدة بدون مشاكل
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.5.5
  flutter_accessibility_service: ^1.2.0
  pusher_channels_flutter: ^2.2.1
  http: ^1.2.2
  crypto: ^3.0.3
  geolocator: ^14.0.3      
  battery_plus: ^7.1.1     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
